#ifndef LOGGER_CONFIG_H_
#define LOGGER_CONFIG_H_

#ifndef LOGGER_ENABLED
#    define LOGGER_ENABLED 1
#endif

#define LOGGER_COMPILE_TIME_DEBUG 1

#define UT_02_LOG_CHANNEL_LEVEL LOGGER_LEVEL_TRACE
#define UT_03_LOG_CHANNEL_LEVEL LOGGER_LEVEL_NOTICE
#define UT_04_LOG_CHANNEL_LEVEL LOGGER_LEVEL_DISABLED
// #define UT_05_LOG_CHANNEL_LEVEL LOGGER_LEVEL_DISABLED - not defined in purpose
#define UT_06_LOG_CHANNEL_LEVEL LOGGER_LEVEL_NOTICE
#define UT_07_LOG_CHANNEL_LEVEL LOGGER_LEVEL_NOTICE
#define UT_08_LOG_CHANNEL_LEVEL LOGGER_LEVEL_NOTICE
#define UT_09_LOG_CHANNEL_LEVEL LOGGER_LEVEL_NOTICE
#define UT_10_LOG_CHANNEL_LEVEL LOGGER_LEVEL_NOTICE


#endif
